export const runtime = 'nodejs'
export const maxDuration = 60

import { NextRequest, NextResponse } from 'next/server'
import JSZip from 'jszip'
import { generatePitchDeck } from '@/lib/ai/pitchdeck'
import { generateGTM } from '@/lib/ai/gtm'
import { generateBrandKit } from '@/lib/ai/brand'
import { generateLogos } from '@/lib/ai/logos'

export async function GET(_req: NextRequest, { params }: { params: { id: string } }) {
  try {
    const analysis = await (async () => {
      if (!process.env.NEXT_PUBLIC_SUPABASE_URL) return null
      const { getAnalysis } = await import('@/lib/db/analyses')
      return getAnalysis(params.id)
    })()
    if (!analysis?.idea_summary) return NextResponse.json({ error: 'Analysis not found' }, { status: 404 })

    // Generate all assets in parallel
    const [pitchBuffer, gtmData, brandKit] = await Promise.all([
      generatePitchDeck(analysis, null),
      generateGTM(analysis),
      generateBrandKit(analysis, analysis.idea_summary)
    ])

    // Generate logos after brand kit so we have real colors
    const logoSVGs = await generateLogos(
      brandKit?.name || analysis.idea_summary || '',
      analysis.idea_summary || '',
      brandKit?.primary_color || '#C8102E',
      brandKit?.accent_color || '#f2ede8',
      brandKit?.tagline || ''
    )

    // Build ZIP
    const zip = new JSZip()

    // Pitch deck
    zip.file('pitch-deck.pptx', Buffer.from(pitchBuffer))

    // GTM playbook as markdown
    const gtmMd = `# GTM Playbook — ${analysis.idea_summary}

## Positioning
${gtmData.positioning_statement}

## Target Channels
${gtmData.target_channels?.map((c: any) => `### ${c.channel}\n${c.rationale}\n**First action:** ${c.first_action}`).join('\n\n')}

## Days 1-30
${gtmData.day_1_to_30?.map((w: any) => `### ${w.week}: ${w.focus}\n${w.actions?.map((a: string) => `- ${a}`).join('\n')}`).join('\n\n')}

## Days 31-90
${gtmData.day_31_to_90?.map((m: any) => `### ${m.milestone}\n${m.actions?.map((a: string) => `- ${a}`).join('\n')}`).join('\n\n')}

## Pricing Strategy
${gtmData.pricing_strategy}

## Success Metrics
${gtmData.success_metrics?.map((m: any) => `- **${m.metric}**: ${m.target} by ${m.timeline}`).join('\n')}
`
    zip.file('gtm-playbook.md', gtmMd)

    // Brand kit as markdown
    const brandMd = `# Brand Identity — ${brandKit.name}

## Brand Name
${brandKit.name}

## Tagline
${brandKit.tagline}

## Positioning
${brandKit.positioning}

## Voice & Tone
- **Tone:** ${brandKit.voice_tone}
- **Personality:** ${brandKit.voice_personality}
- **Avoid:** ${brandKit.voice_avoid}

## Colors
- **Primary:** ${brandKit.primary_color}
- **Accent:** ${brandKit.accent_color}

## Typography
- **Display:** ${brandKit.font_display}
- **Body:** ${brandKit.font_body}

## Ideal Customer Profile
${brandKit.icp}

## Elevator Pitch
${brandKit.elevator_pitch}

## Domain Ideas
${brandKit.domain_ideas?.map((d: string) => `- ${d}`).join('\n')}
`
    zip.file('brand-kit.md', brandMd)

    // ZenBusiness referral
    const zenMd = `# Form Your LLC — Next Steps

Your idea has been analyzed. If you're ready to make it official:

## Recommended: ZenBusiness
- Form your LLC in 10 minutes
- $0 + state fees on their starter plan
- Registered agent included first year
- Bank account setup included

**Start here:** https://zenbusiness.com/?ref=viabl

## What you'll need:
- Business name (see brand-kit.md for suggestions)
- State of formation (where you live or operate)
- Registered agent address (ZenBusiness provides this)
- ~30 minutes total

## After forming your LLC:
1. Open a business bank account (Mercury.co is free + great for startups)
2. Get an EIN from IRS.gov (free, takes 5 minutes)
3. Set up accounting (Wave is free for early stage)
4. Get business insurance (Next Insurance is fast + affordable)
`
    zip.file('next-steps-llc.md', zenMd)

    // Analysis summary
    const analysisMd = `# Viability Analysis — ${analysis.idea_summary}

**Overall Score:** ${analysis.overall_score}/100
**Verdict:** ${analysis.verdict}

## Summary
${analysis.summary}

## Market Size
${analysis.market_size}

## Competition
${analysis.competition}

## Top Risks
${analysis.top_risks?.map((r: string) => `- ${r}`).join('\n')}

## Next Steps
${analysis.next_steps?.map((s: string, i: number) => `${i+1}. ${s}`).join('\n')}

---
Generated by Viabl · viabl.co
`
    zip.file('viability-analysis.md', analysisMd)

    // Add logo SVGs
    if (logoSVGs?.length) {
      logoSVGs.forEach((svg: string, i: number) => {
        if (svg) zip.file("logo-concept-" + String(i+1) + ".svg", svg)
      })
    }

    const zipBuffer = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' })

    return new NextResponse(Buffer.from(zipBuffer as any), {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="viabl-launch-kit-${params.id}.zip"`,
        'Cache-Control': 'no-store',
      }
    })
  } catch (err) {
    console.error('[launchkit]', err)
    return NextResponse.json({ error: 'Launch kit generation failed' }, { status: 500 })
  }
}
